services:
  app:
    build: .
    container_name: todo-app
    environment:
      - JWT_SECRET=your_jwt_secret
      - DATABASE_URL=postgresql://postgres:password@db:5432/todoapp?schema=public
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:latest
    container_name: todo-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todoapp
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
