### GET /
GET http://localhost:3000/todos

### Register a user POST /auth/register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "example@gmail.com",
  "password": "testpassword"
}

### Login a user POST /auth/login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "example@gmail.com",
  "password": "testpassword"
}